In [26]:
import numpy as np
rg = np.random.default_rng(1)

In [ ]:
np.array((1, 2, 3, 4))
np.array([(1.5, 2, 3), (4, 5, 6)], dtype=complex)
np.empty((2, 3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.linspace(0, 2, 9).shape
from numpy import pi
x=np.linspace(0, 2 * pi, 100)
np.sin(x)


(100,)

In [25]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c[..., 2]  # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

In [36]:
a = np.floor(10 * rg.random((3, 4)))
a.ravel()

array([8., 0., 8., 1., 3., 3., 6., 1., 3., 0., 2., 4.])

堆叠

In [60]:
a = np.arange(0, 4).reshape(2, 2)  # create a 2D array
b = np.arange(4, 8).reshape(2, 2)
print(a, end='\n\n')
print(b, end='\n\n')

print(np.vstack((a, b)), end='\n\n')  # stack arrays vertically
print(np.hstack((a, b)), end='\n\n')  # stack arrays horizontally
print(np.column_stack((a,b)), end='\n\n')

c=a.reshape(4)  # reshape to a column vector
d=b.reshape(4)  # reshape to a row vector
print(np.column_stack((c,d)), end='\n\n')

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1 4 5]
 [2 3 6 7]]

[[0 1 4 5]
 [2 3 6 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]



In [65]:
a = np.arange(0, 4)
b = np.arange(4, 8)

print(a[:, np.newaxis], end='\n\n')  # add a new axis to a
print(np.column_stack((a[:], b[:])), end='\n\n')
print(np.hstack((a[:, np.newaxis], b[:, np.newaxis])), end='\n\n')  # the result is the same

[[0]
 [1]
 [2]
 [3]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]



In [ ]:
a = np.floor(10 * rg.random((2, 12)))
print(a, end="\n\n")
print(np.hsplit(a, 3), end="\n\n")
print(np.hsplit(a, (3, 4)), end="\n\n")

[[8. 6. 8. 6. 3. 7. 0. 4. 3. 4. 1. 2.]
 [5. 3. 7. 6. 8. 7. 6. 2. 7. 2. 0. 9.]]

[array([[8., 6., 8., 6.],
       [5., 3., 7., 6.]]), array([[3., 7., 0., 4.],
       [8., 7., 6., 2.]]), array([[3., 4., 1., 2.],
       [7., 2., 0., 9.]])]

[array([[8., 6., 8.],
       [5., 3., 7.]]), array([[6.],
       [6.]]), array([[3., 7., 0., 4., 3., 4., 1., 2.],
       [8., 7., 6., 2., 7., 2., 0., 9.]])]



In [69]:
s=a[:,1:3]
s[:]=10
s

array([[10., 10.],
       [10., 10.]])

boradcast

In [75]:
a = np.ones((2, 3, 4))  # shape (2, 3, 4)
b = np.array([1, 2, 3, 4])  # shape (4,)
s = a + b
print(a)
print('-----')
print(s)  # 输出: (2, 3, 4)
print('-----')
print(s-a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
-----
[[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]

 [[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]]
-----
[[[1. 2. 3. 4.]
  [1. 2. 3. 4.]
  [1. 2. 3. 4.]]

 [[1. 2. 3. 4.]
  [1. 2. 3. 4.]
  [1. 2. 3. 4.]]]


In [76]:
a = np.array([2,2,2])
b = np.array([2,2])
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 